#pragma once
// Provenance of THIS binary, so anyone reading logcat can tell exactly what is
// baked into the build currently installed on the shared headset.
//
// SAVR_BUILD_ORIGIN: which working tree produced the .so.
// SAVR_SHARED_SYNC : for fork builds, the shared-tree state that was mirrored
//                    in before this build. Regenerated by tools/build.sh from
//                    the shared tree's newest source mtime; a plain-shared-tree
//                    build reports "self".
#ifndef SAVR_BUILD_ORIGIN
#define SAVR_BUILD_ORIGIN "unknown"
#endif
#ifndef SAVR_SHARED_SYNC
#define SAVR_SHARED_SYNC "unknown"
#endif
